### ISSUE TITLE
can not marshal *gocql.UUID into uuid

### ISSUE THREAD

**Issue by nt3rp** [relops/cqlr#4]
I have a struct that looks like this:

```
type MyStruct struct {
    Id        gocql.UUID         `json:"id"                     cql:"id"`
    Name      string             `json:"name"                   cql:"name"`
}
```

And my code looks like this:

```
func (m *MyStruct) myFunc() error {
    id, err := gocql.RandomUUID()
    if err != nil {
        return err
    }
    qs := `INSERT INTO myTable (id, name) VALUES(?,?)`
    m.Id = id
    err = cqlr.Bind(qs, m).Exec(session)

    return err
}
```

But when I run my code, I get this error:

```
can not marshal *gocql.UUID into uuid
```

What is going on?

**Comment by 0x6e6562** [comment]
How is the variable `a` defined?

**Comment by nt3rp** [comment]
Er, sorry, that should be an `m`. I'll edit.

**Comment by nt3rp** [comment]
If it helps, when I switch [these lines around](https://github.com/relops/cqlr/blob/master/cqlr.go#L128), everything seems to work, but admitedly I'm new to all this:

```
if f.CanInterface() {
    values[i] = f.Interface()
} else if f.CanAddr() {
    values[i] = f.Addr().Interface()
}
```

Not sure if that's a coincidence or not.

**Comment by 0x6e6562** [comment]
That's a very good question - I'm not sure why the underlying UUID type alias to a byte slice behaves in that way - this sounds like a question for the go-nuts list. That said, I think it's fine to swap the lines around, since it doesn't appear to have any other adverse effects. I've added a test case to cover this scenario going forwards. Let me know if 1998794 resolves your issue.

**Comment by nt3rp** [comment]
That appears to resolve the issue. :)

**Comment by 0x6e6562** [comment]
Great, thank you for reporting this and identifying the root cause.
