### ISSUE TITLE
Docs or examples for beginners?

### ISSUE THREAD

**Issue by chmac** [relops/cqlr#5]
Firstly, thanks for cqlr, seems to be the missing piece for easily binding structs to cql queries.

I'm starting out with Go, and still coming to terms with much of it. Tried reading the source to figure out what the various functions do, but the lack of documentation and slightly opaque variable names made for pretty tough reading.

Are you open to adding some code comments or a few more examples beyond the existing readme? I would offer to submit a pull request, but I'm struggling to understand the code...

**Comment by 0x6e6562** [comment]
Fundamentally all pull requests are welcome, but it sounds like you first need to see some basic examples to get that initial "aha" moment. Have you looked at the examples from `cqlr_test.go`? If that is not sufficient, would you like to describe a CQL scenario that I could translate into a concrete cqlr example for you?

**Comment by chmac** [comment]
Thanks for the fast reply. I missed the email notification, so spent the day writing loooooong `.Scan()` calls. :-)

After a day of working gocql I think I'm getting a handle on the idea behind cqlr. I've just tried a little refactoring, and read through the code again. It looks like cqlr doesn't support nested structs, is that correct?

My schema looks like (in JSON) `{"foo": {"some": "value"}}` and my Cassandra schema looks like `foo.some = value`. I think I'll experiment with custom marhalling another day... :-)

**Comment by 0x6e6562** [comment]
Are you referring to user defined types (as of Cassandra 2.1) or the fact that you would like to map columns of a row in Cassandra to fields of an embedded struct?

Also, is it possible for you to share the CQL create table statement and the corresponding struct definition you'd like to map?

**Comment by chmac** [comment]
Thanks for the very kind offer, and sorry it took me so long to follow up. I'm new to Go, Cassandra and all the associated tools, so I don't have the CQL statement that I had in mind. I'm coming from a MySQL / Mongo world, so apologies if I've missed something fundamental.

I had in mind that my struct would look something like this:

``` go
type Foo struct {
  X int
  Y int
}
type Bar struct {
  Foo Foo
  Z int
}
```

Then my Cassandra columns would be `foo.x`, `foo.y`, and `z`.

The same expressed in JSON (with which I'm much more familiar!) would be:

``` json
{
  "foo": {
    "x": 1,
    "y": 2
  },
  "z": 3
}
```

Then the equivalent MySQL `CREATE TABLE` query would be:

``` sql
CREATE TABLE `bar` (
  `foo.x` INT,
  `foo.y` INT,
  `z` INT
);
```

I don't think Cassandra supports this kind of "nested" objects by default, as I understand it, Cassandra stores keys: values where the values are simple types. We have some nested objects like this that we eventually render in JSON, and I was looking at different ways to store the data in Cassandra. I figured dot separating the names might make sense, and would be easy to understand for people coming from the Mongo world (like myself).

Thanks again for the help, really appreciate it.

**Comment by 0x6e6562** [comment]
As of version 2.1, Cassandra does support the notion of [user defined types](http://www.datastax.com/documentation/cql/3.1/cql/cql_using/cqlUseUDT.html), which would allow to nest your data in a way that is isomorphic to Mongo (albeit with an explicit schema).

Note the usage of the `frozen` keyword - this means that the chapter on UDTs and nested structures has not been completely written - the Cassandra 3 dev branch is going to change the internal storage layout of nested structures to make them more amenable to indexing. So because they know that this is going to change, they introduced this keyword to assist with backwards compatibility for apps that transitioned to the 2.1.x UDT support.

That all being said, neither `clqr` nor `gocql` have any support for the 2.1 nested types right now. It is notionally on the road map for gocql - meaning that if people start caring about this enough and bugging us, then we'll look into supporting it. To support it, we'll need to enhance the marshalling layer, which involves work. Since nobody has thus far voiced a strong opinion, this remains on the todo list.

So I'm not sure how much that helps you :-(

**Comment by 0x6e6562** [comment]
That all being said about the lack of UDT support in `cqlr` or `gocql`, the last MySQL-esque example is probably implementable with a change to `cqlr`, because the nested structure is just flattened into a simple table. Because `cqlr` is layered approach, it can most probably achieve this without having to change anything in `gocql`. But many people would argue that it's a poor man's variant of nested data structures.

**Comment by chmac** [comment]
Aha, interesting. Thanks for the insight into Cassandra. I didn't know about nested data types in Cassandra, so assumed we'd need to flatten the structure. I hadn't quite figured out how we were going to flatter arrays, but structs seemed like they would work well enough.

I'm coming around to the idea that I probably want to store data as simple `key: value` pairs in Cassandra, and engineer around that. We're starting out with PostgreSQL to get the project going, so might not come back to this topic for a while, at least on this project. Cassandra 3 might be out and have solved this by then. :-)

Thanks again for the help, will close the issue now and come back to it if I ever get round to a PR.
